pipeline {
    agent any
     tools {
        // This injects the Java 21 paths you configured in Step 1
        jdk 'JDK21'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
		 dir('/var/lib/jenkins/workspace/sprint1test1/starter') {
                sh 'mvn -f ./pom.xml -B clean package'
		}
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit 'target/test-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
